spring.application.name=smart-travel-management-system
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=SYSTEM
spring.datasource.password=Admin@123
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto= update


# PayPal Configuration
paypal.mode=sandbox
paypal.client.id=AaxAT6TrdplRJbyf8dcSMIfFwNglxW_anqQZ4xT3MwJeqK-AJ5A_Tk6mS4AXSYwcjo1RrU9aiJmIqXPr
paypal.client.secret=EFmcD_iNK-g7NVf4YNRZ6QpujST0JrLmo-0QAoQm-Wx_zsycQaVSqCG5Cv71ZQQP8OceKUA72M849nKr